### ISSUE TITLE
Neptune Deployment optimization

### ISSUE THREAD

**Issue by kason-huang** [edgeai-neptune/neptune#35]
1. GM and LC should use deployment rather than pod to deploy in order to get the deployment's feature.
2. GM's rbac should not directly use the defautl service account, the recommend way is create a new service account for GM.
3. The neptune-related resource objects such as gm and lc should be deployed in an independent namespace.
4. The GM and LC deployment should configure their limit and request.

**Comment by llhuii** [comment]
except that LC is kept as daemonset, the other suggestions are accepted
